#!/usr/bin/env bash

cd ~/workspace/dotfiles
ln -s $PWD/.bash_aliases ~/.bash_aliases
ln -s $PWD/.bash_vars ~/.bash_vars
ln -s $PWD/.bashrc_user ~/.bashrc_user
ln -s $PWD/.gitconfig ~/.gitconfig
touch ~/.bash_vars_local
