#!/usr/bin/env bash

cd dotfiles/
git submodule update --init
ln -s $PWD/.aliases ~/.aliases
ln -s $PWD/.gitconfig ~/.gitconfig
ln -s $PWD/.zshrc_user ~/.zshrc_user
echo "source \$HOME/.zshrc_user" >> ~/.zshrc

echo "Done!"
